version: "3.9"

services:
  # docker exec -i $(docker ps --filter name=mysql -q) sh -c 'exec mysql -uroot -p"$MYSQL_ROOT_PASSWORD"' < /tmp/dump.sql
  mysql:
    image: mysql:5.7.12
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677
    networks:
      - network_app
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 2G
        reservations:
          cpus: "0.25"
          memory: 512M

  backend:
    build:
      context: backend
      dockerfile: ../dockerfiles/backend.Dockerfile
    networks:
      - network_app
    env_file: backend/.env
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - mysql
    links:
      - "mysql:mysql"
    volumes:
      - ./backend/src:/usr/src/app/src:ro
      - ./backend/test:/usr/src/app/test:ro

networks:
  network_app:
    name: real-estate-finder-network
